# Generated by Django 3.0.4 on 2020-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200511_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_models',
            old_name='date_conatact',
            new_name='date',
        ),
        migrations.AddField(
            model_name='contact_models',
            name='email',
            field=models.EmailField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
