# Generated by Django 3.0.4 on 2020-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_models_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_models',
            name='confirmation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
