# Generated by Django 3.0.4 on 2020-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200511_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_models',
            name='Surname',
            field=models.CharField(blank=True, default=True, max_length=200),
            preserve_default=False,
        ),
    ]
