# Generated by Django 3.0.4 on 2020-05-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200511_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_models',
            name='confirmation',
            field=models.BooleanField(blank=True),
        ),
    ]
