# Generated by Django 3.0.4 on 2020-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact_models_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_models',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contact_models',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact_models',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='contact_models',
            name='confirmation',
            field=models.BooleanField(null=True),
        ),
    ]
