# Generated by Django 3.0.4 on 2020-05-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedadies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
